title: >
  <span style="background-color: rgba(11, 110, 117, 0.75); padding: 10px; color: white; border-radius: 5px;">
    Databases Unlocked: A Beginner's Journey
  </span>

comment: >
  <br>
  <span style="background-color: rgba(255, 140, 66, 0.75); padding: 8px; color: white; border-radius: 5px;">
    Interactive Database Systems Course with LiaScript
  </span>

logo: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/assets/img/logo/main.jpg

footer: >
  <hr>
  <p>
    <strong>Databases Unlocked</strong> – Eine praxisnahe Einführung in die Welt der Datenbanken<br>
    Bachelor-Studierende der Informatik (3.–5. Semester)<br>
    <br>
    Erstellt mit <a href="https://liascript.github.io" target="_blank">LiaScript</a> – 
    Markup für interaktive Open Educational Resources
  </p>

meta:
  title: Databases Unlocked - Interactive Database Systems Course
  description: >
    Praxisnahe Einführung in Datenbanksysteme: Von Dateiformaten über Key-Value, 
    Document und Column Stores bis zu relationalen Datenbanken mit SQL. 
    Alle Konzepte direkt im Browser mit Hands-on-Beispielen.

# Main course collection
collection:
  # Introduction section
  - html: >
      <div style="padding: 20px; background-color: rgba(11, 110, 117, 0.1); border-radius: 8px; margin: 20px 0;">
        <h2>📚 Über diesen Kurs</h2>
        <p>
          Diese Vorlesung bietet eine <strong>praxisnahe Einführung in die Welt der Datenbanken</strong> 
          und vermittelt einen systematischen Überblick über unterschiedliche Paradigmen und ihre Einsatzszenarien.
        </p>
        <p>
          Beginnend bei einfachen Datenquellen wie Textdateien, CSV, JSON, YAML oder TOML werden schrittweise 
          moderne Systeme vorgestellt – von Key-Value Stores über Object Stores und Column Stores bis hin zu 
          <strong>relationalen Datenbanken mit SQL</strong> und graphbasierten Ansätzen.
        </p>
        <p>
          <strong>Besonderheit:</strong> Alle Paradigmen werden mit Hands-on-Beispielen direkt im Browser 
          erlebbar (über LiaScript und DBMS wie DuckDB-Wasm, SQLite-Wasm, IndexedDB, PouchDB).
        </p>
      </div>

  # Course Start / Orientation
  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/0-lecture.md
    tags:
      - Einführung
      - Übersicht
      - Organisatorisches
      
  # Block 1: Paradigmen-Überblick (kompakt)
  - html: >
      <hr>
      <h2 style="color: #0B6E75;">Block 1: Daten-Paradigmen – Vom File zum Column Store</h2>
      <p>
        In diesem Block lernen Sie verschiedene Datenbank-Paradigmen kennen: 
        Von einfachen Dateiformaten über Key-Value und Document Stores bis zu Column Stores.
        Jedes Paradigma wird mit praktischen Beispielen im Browser demonstriert.
      </p>

 
  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/1-lecture.md
    title: "L1: Daten & Serialisierung + DIKW"
    tags:
      - CSV
      - JSON
      - YAML
      - Serialisierung
      - DIKW
      - Grundlagen

  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/2-lecture.md
    title: "L2: Key-Value Stores"
    tags:
      - Key-Value
      - Redis
      - NoSQL
      - Cache
      - Performance

  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/3-lecture.md
    title: "L3: Document Stores"
    tags:
      - Document Store
      - MongoDB
      - PouchDB
      - Indizes
      - Abfragen
      - NoSQL
      - Synchronisation

  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/4-lecture.md
    title: "L4: Column Stores"
    tags:
      - Column Store
      - DuckDB
      - Analytics
      - OLAP
      - Spaltenorientiert
  
  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/5-lecture.md
    title: "L5: Relationale Datenbanken (SQL) – Von der Idee zum Model"
    tags:
      - Relationale Datenbanken
      - SQL
      - Normalisierung
      - ER-Modell
      - Datenmodellierung

  # Block 2: Relationale Grundlagen (coming soon)
  - html: >
      <hr>
      <h2 style="color: #0B6E75;">Block 2: Relationale Grundlagen</h2>
      <p>
        <strong>Block 2 startet mit einer interaktiven Live-Session (L7):</strong><br>
        <span style="color: #FF8C42; font-weight: bold;">SQL Introduction & Query Data (SELECT)</span> – Hands-on, direkt im Browser.<br>
        Relationales Modell, Relationale Algebra und weitere SQL-Themen folgen schrittweise.<br>
        Die Materialien für Block 2 werden nach und nach ergänzt.
      </p>


  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/7-lecture.md
    title: "L7: SQL Introduction & Query Data (SELECT)"
    tags:
      - SQL
      - Hands-on
      - Live-Session
      - SELECT
      - Query
      - Praxis
    arguments:
      - pdf-timeout: 120000
  
  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/7-lecture-full.md
    title: "L7: SQL Introduction & Query Data (SELECT) – Vollversion"
    tags:
      - SQL
      - SELECT
      - Query
      - Praxis
    arguments:
      - pdf-timeout: 120000
  
  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/8-lecture.md
    title: "L8: SQL Data Definition (DDL) & Manipulation (DML)"
    tags:
      - SQL
      - DDL
      - DML
      - ALTER
      - CREATE
      - INSERT
      - UPDATE
      - DELETE
    arguments:
      - pdf-timeout: 120000

  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/8-lecture-full.md
    title: "L8-Complete: SQL Data Definition (DDL) & Manipulation (DML)"
    tags:
      - SQL
      - DDL
      - DML
      - ALTER
      - CREATE
      - INSERT
      - UPDATE
      - DELETE
    arguments:
      - pdf-timeout: 120000

  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/9-lecture.md
    title: "L9: Normalisierung & ER-Diagramme"
    tags:
      - Normalisierung
      - ER-Diagramme
      - 1NF
      - 2NF
      - 3NF
      - Hands-on
      - Live-Session
    arguments:
      - pdf-timeout: 120000


  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/9-lecture-full.md
    title: "L9-Complete: Normalisierung & ER-Diagramme"
    tags:
      - Normalisierung
      - ER-Diagramme
      - 1NF
      - 2NF
      - 3NF
      - Hands-on
      - Live-Session
    arguments:
      - pdf-timeout: 120000


  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/10-lecture.md
    title: "L10: Mehr FROM Subqueries, CTEs, Joins"
    tags:
      - Joins
      - SQL
      - Subqueries
      - CTEs
      - Hands-on
      - Live-Session
    arguments:
      - pdf-timeout: 120000

  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/10-lecture-full.md
    title: "L10-Complete: Mehr FROM Subqueries, CTEs, Joins"
    tags:
      - Joins
      - SQL
      - Subqueries
      - CTEs
      - Hands-on
      - Live-Session
    arguments:
      - pdf-timeout: 120000

  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/12-lecture.md
    title: "L12: Indexe & Performance"
    tags:
      - SQL
      - Index
      - IMDB
      - Performance
      - Analyse
    arguments:
      - pdf-timeout: 120000

  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/13-lecture.md
    title: "L13: Advanced SQL – SET Operations & Views"
    tags:
      - SQL
      - SET Operations
      - Views
      - E-Commerce
    arguments:
      - pdf-timeout: 120000
        
  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/14-lecture.md
    title: "L14: Transaktionen & ACID"
    tags:
      - SQL
      - Transaktionen
      - ACID
      - Isolation
      - Konsistenz
    arguments:
      - pdf-timeout: 120000
        
  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/15-lecture.md
    title: "L15: Funktionen & Trigger"
    tags:
      - SQL
      - Funktionen
      - Trigger
      - Automatisierung
      - Konsistenz
    arguments:
      - pdf-timeout: 120000

  # Block 3: Technologien – APIs & KI-Integration
  - html: >
      <hr>
      <h2 style="color: #0B6E75;">Block 3: Technologien – Datenbankzugriff über APIs & KI</h2>
      <p>
        In diesem Block lernen Sie moderne Technologien kennen, um auf Datenbanken zuzugreifen:
        Von <strong>KI-gestützten Abfragen mit MCP</strong> über klassische <strong>REST-APIs</strong>
        bis zu <strong>GraphQL</strong> für flexible Datenabfragen.
      </p>

  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/mcp-tutorial.md
    title: "MCP Tutorial: KI-gestützte Datenbankabfragen"
    tags:
      - MCP
      - Model Context Protocol
      - KI
      - GitHub Copilot
      - IMDB
      - SQLite
      - Tutorial
      - Hands-on
    arguments:
      - pdf-timeout: 120000

  # Additional Resources
  - html: >
      <hr>
      <h2 style="color: #FF8C42;">📖 Zusatzmaterialien</h2>
      <p>Weitere Ressourcen und Primer für die Vorlesung</p>

  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/sql-cheat-sheet.md
    title: "SQL Cheat Sheet"
    tags:
      - SQL
      - Primer
      - Grundlagen
      - Abfragen
      - DDL
      - DML
      - SQL

  - url: https://raw.githubusercontent.com/andre-dietrich/Datenbankensysteme-Vorlesung/refs/heads/main/materials/javascript-primer.md
    title: "JavaScript Primer"
    tags:
      - JavaScript
      - Primer
      - Grundlagen
      - Browser


  # Learning Objectives Summary
  - html: >
      <hr>
      <div style="padding: 20px; background-color: rgba(255, 140, 66, 0.1); border-radius: 8px; margin: 20px 0;">
        <h2>🎯 Lernziele</h2>
        <p>Nach Abschluss der Vorlesung können Sie:</p>
        <ol>
          <li><strong>Grundlagen der Datenbank-Paradigmen</strong> verstehen und typische Einsatzszenarien erklären</li>
          <li><strong>Relationale Datenbanken mit SQL anwenden</strong>, einschließlich Datenmodellierung und Normalisierung</li>
          <li><strong>Praktische Erfahrung sammeln</strong> mit verschiedenen Datenbanksystemen direkt im Browser</li>
          <li><strong>Kernkonzepte wie ACID und Transaktionen</strong> analysieren und vergleichen</li>
          <li><strong>Stärken und Schwächen</strong> unterschiedlicher Ansätze kritisch beurteilen</li>
        </ol>
      </div>
